/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.form;

import domain.Racun;
import domain.Zaposleni;
import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import logic.Controller;
import ui.component.RacunTableModel;

/**
 *
 * @author Korisnik
 */
public class FormMain extends javax.swing.JFrame {
    
    private Zaposleni user;

    /**
     * Creates new form FormMain
     */
    public FormMain(Zaposleni z) {
        this.user = z;
        initComponents();
        setTitle("F1 TicketSystem: " + z.getIme()+ " " + z.getPrezime());
        setExtendedState(MAXIMIZED_BOTH);
        prepareTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNaslov = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRacuni = new javax.swing.JTable();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenuMeni = new javax.swing.JMenu();
        jMenuKreirajRacun = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNaslov.setText("Racuni izdati od strane zaposlenog");

        jTableRacuni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableRacuni);

        jMenuMeni.setText("Meni");

        jMenuKreirajRacun.setText("Kreiraj Racun");
        jMenuKreirajRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuKreirajRacunActionPerformed(evt);
            }
        });
        jMenuMeni.add(jMenuKreirajRacun);

        jMenuBar2.add(jMenuMeni);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuKreirajRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuKreirajRacunActionPerformed
        try{
            FormCreateBill forma = new FormCreateBill(this, true, user);
            forma.setVisible(true);
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuKreirajRacunActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuKreirajRacun;
    private javax.swing.JMenu jMenuMeni;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRacuni;
    private javax.swing.JLabel lblNaslov;
    // End of variables declaration//GEN-END:variables

    private void prepareTable() {
        try{
            List<Racun> racuni = new ArrayList<>();
            Controller controller = new Controller();
            racuni = controller.vratiRacunePoZaposlenom(user);
            RacunTableModel model = new RacunTableModel(racuni);
            jTableRacuni.setModel(model);
            
            DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();
            cellRenderer.setHorizontalAlignment(SwingConstants.CENTER);
            for(int i = 0; i<jTableRacuni.getColumnCount(); i++){
                jTableRacuni.getColumnModel().getColumn(i).setCellRenderer(cellRenderer);
            }
            
        }
        catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Greska prilikom ucitavanja podataka u tabelu!", "Greska!",JOptionPane.ERROR_MESSAGE);
        }
    }
}
