/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui.form;

import domain.KategorijaOsobe;
import domain.Osoba;
import domain.Racun;
import domain.Sektor;
import domain.StavkaRacuna;
import domain.Staza;
import domain.TipKarte;
import domain.Zaposleni;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import logic.Controller;
import ui.component.StavkaRacunaTableModel;

/**
 *
 * @author Korisnik
 */
public class FormCreateBill extends javax.swing.JDialog {
    
    private Zaposleni user;

    /**
     * Creates new form FormCreateBill
     */
    public FormCreateBill(java.awt.Frame parent, boolean modal,Zaposleni z) {
        super(parent, modal);
        this.user=z;
        initComponents();
        setLocationRelativeTo(null);
        setTitle("F1 TicketSystem: Kreiranje racuna" );
        prepareTable();
        fillTracks();
        fillDate();
        fillSectors();
        fillDiscount();
        
        try {
            fillPrice();
        } catch (Exception ex) {
            System.getLogger(FormCreateBill.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        fillTotalPrice();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDatum = new javax.swing.JLabel();
        txtDatum = new javax.swing.JTextField();
        lblImeKupca = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbTipKarte = new javax.swing.JComboBox<>();
        btnDodajStavku = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        btnObrisiStavku = new javax.swing.JButton();
        btnKreirajRacun = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCena = new javax.swing.JLabel();
        lblKolicina = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbTrajanje = new javax.swing.JComboBox<>();
        cbSektor = new javax.swing.JComboBox<>();
        txtCena = new javax.swing.JTextField();
        txtKolicina = new javax.swing.JTextField();
        txtIznos = new javax.swing.JTextField();
        lblUkupanIznos = new javax.swing.JLabel();
        lblUkupanIznos3 = new javax.swing.JLabel();
        cbStaza = new javax.swing.JComboBox<>();
        lblPopust = new javax.swing.JLabel();
        txtPopust = new javax.swing.JTextField();
        txtUkupanIznos = new javax.swing.JTextField();
        txtImeKupca = new javax.swing.JTextField();
        lblPrezimeKupca = new javax.swing.JLabel();
        txtPrezimeKupca = new javax.swing.JTextField();
        lblTelefon = new javax.swing.JLabel();
        txtTelefon = new javax.swing.JTextField();
        lblKategorija = new javax.swing.JLabel();
        cbKategorija = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblDatum.setText("Datum kupovine:");

        txtDatum.setEditable(false);

        lblImeKupca.setText("Ime:");

        lbl1.setText("Dodavanje stavki kupovine u racun");

        jLabel1.setText("Tip karte:");

        cbTipKarte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General Admission", "Grandstand", "Paddock Pass" }));
        cbTipKarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipKarteActionPerformed(evt);
            }
        });

        btnDodajStavku.setText("Dodaj Stavku");
        btnDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStavkuActionPerformed(evt);
            }
        });

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavke);

        btnObrisiStavku.setText("Obrisi Stavku");

        btnKreirajRacun.setText("Kreiraj Racun");
        btnKreirajRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajRacunActionPerformed(evt);
            }
        });

        jLabel2.setText("Trajanje:");

        jLabel3.setText("Sektor:");

        lblCena.setText("Cena:");

        lblKolicina.setText("Kolicina:");

        jLabel6.setText("Iznos:");

        cbTrajanje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 day", "2 day", "3 day" }));
        cbTrajanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTrajanjeActionPerformed(evt);
            }
        });

        txtCena.setEditable(false);

        txtKolicina.setText("1");
        txtKolicina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKolicinaActionPerformed(evt);
            }
        });

        txtIznos.setEditable(false);

        lblUkupanIznos.setText("Ukupan iznos:");

        lblUkupanIznos3.setText("Staza:");

        lblPopust.setText("Popust:");

        txtPopust.setEditable(false);

        txtUkupanIznos.setEditable(false);

        lblPrezimeKupca.setText("Prezime:");

        lblTelefon.setText("Broj telefona:");

        lblKategorija.setText("Kategorija");

        cbKategorija.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "REGULAR", "PREMIUM", "VIP" }));
        cbKategorija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKategorijaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtDatum))
                            .addComponent(lbl1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDodajStavku)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbTipKarte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbTrajanje, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbSektor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblImeKupca, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUkupanIznos)
                                    .addComponent(txtImeKupca)
                                    .addComponent(txtTelefon))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblKolicina, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                    .addComponent(lblCena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblUkupanIznos3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPopust, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblKategorija, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCena)
                                    .addComponent(txtKolicina)
                                    .addComponent(txtIznos)
                                    .addComponent(cbStaza, 0, 133, Short.MAX_VALUE)
                                    .addComponent(txtPopust)
                                    .addComponent(cbKategorija, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPrezimeKupca, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrezimeKupca)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnObrisiStavku)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKreirajRacun)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatum)
                    .addComponent(lblUkupanIznos3)
                    .addComponent(cbStaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImeKupca)
                    .addComponent(txtImeKupca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrezimeKupca)
                    .addComponent(txtPrezimeKupca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefon)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKategorija)
                    .addComponent(cbKategorija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUkupanIznos)
                    .addComponent(txtUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPopust)
                    .addComponent(txtPopust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbTipKarte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCena)
                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbTrajanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKolicina)
                    .addComponent(txtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbSektor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDodajStavku)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnObrisiStavku)
                    .addComponent(btnKreirajRacun))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTipKarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipKarteActionPerformed
        try {
            fillPrice();
        } catch (Exception ex) {
            System.getLogger(FormCreateBill.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        fillTotalPrice();
    }//GEN-LAST:event_cbTipKarteActionPerformed

    private void cbTrajanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTrajanjeActionPerformed
        try {
            fillPrice();
        } catch (Exception ex) {
            System.getLogger(FormCreateBill.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        fillTotalPrice();
    }//GEN-LAST:event_cbTrajanjeActionPerformed

    private void txtKolicinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKolicinaActionPerformed
        fillTotalPrice();
    }//GEN-LAST:event_txtKolicinaActionPerformed

    private void btnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStavkuActionPerformed
        try {
            String nazivKarte =(String) cbTipKarte.getSelectedItem();
            String trajanje = (String) cbTrajanje.getSelectedItem();
            Sektor sektor = (Sektor)cbSektor.getSelectedItem();
            double cena = Double.parseDouble(txtCena.getText());
            int kol = Integer.parseInt(txtKolicina.getText());
            double iznos = Double.parseDouble(txtIznos.getText());
            Controller c = new Controller();
            TipKarte tk = c.vratiTipKarte(nazivKarte, trajanje, cena);
            StavkaRacuna sr = new StavkaRacuna(kol, cena, iznos, sektor, tk);
            StavkaRacunaTableModel model = (StavkaRacunaTableModel) tblStavke.getModel();
            model.addStavka(sr);
            String popustText = txtPopust.getText();
            double popust = Double.parseDouble(popustText.replace("%", ""));
            List<StavkaRacuna> stavke = model.getStavke();
            double total = 0;
            for(int i=0;i<stavke.size();i++){
                double ukupno = 0;
                ukupno += stavke.get(i).getIznos();
                double mul = (100-popust)/100;
                total += ukupno*mul;    
            }
            txtUkupanIznos.setText(String.valueOf(total));
            
        } catch (Exception ex) {
            System.getLogger(FormCreateBill.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        
    }//GEN-LAST:event_btnDodajStavkuActionPerformed

    private void btnKreirajRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajRacunActionPerformed
        try {
            String fName = txtImeKupca.getText();
            String lName = txtPrezimeKupca.getText();
            int tel = Integer.valueOf(txtTelefon.getText());
            String nazivKategorije = cbKategorija.getSelectedItem().toString();
            Controller controller = new Controller();
            KategorijaOsobe cat = controller.vratiKategorijuOsobe(nazivKategorije);
            Osoba o = new Osoba(fName, lName, tel,cat);
            Osoba kupac = controller.kreirajOsobu(o);
            StavkaRacunaTableModel model = (StavkaRacunaTableModel)tblStavke.getModel();
            List<StavkaRacuna> stavke = model.getStavke();
            Staza track = Staza.valueOf(cbStaza.getSelectedItem().toString());
            String datumStr = txtDatum.getText();
            LocalDate datumKup = LocalDate.parse(datumStr);
            String popustText = txtPopust.getText();
            double popust = Double.parseDouble(popustText.replace("%", ""));
            double ukupanTrosak = Double.parseDouble(txtUkupanIznos.getText());
            Racun r = new Racun(ukupanTrosak, datumKup, popust, track, user, kupac);
            Racun kreiran = controller.instancirajRacun(r);
            for(int i =0;i<stavke.size();i++){
                StavkaRacuna s = stavke.get(i);
                s.setRb((long)(i+1));
                s.setRacun(kreiran);
                controller.kreirajStavku(s);
            }
            JOptionPane.showMessageDialog(this, "Uspesno kreiran racun!", "Kreiranje racuna: Uspesno!", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception ex) {
            System.getLogger(FormCreateBill.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnKreirajRacunActionPerformed

    private void cbKategorijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKategorijaActionPerformed
        fillDiscount();
    }//GEN-LAST:event_cbKategorijaActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajStavku;
    private javax.swing.JButton btnKreirajRacun;
    private javax.swing.JButton btnObrisiStavku;
    private javax.swing.JComboBox<String> cbKategorija;
    private javax.swing.JComboBox<Object> cbSektor;
    private javax.swing.JComboBox<Object> cbStaza;
    private javax.swing.JComboBox<String> cbTipKarte;
    private javax.swing.JComboBox<String> cbTrajanje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lblCena;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblImeKupca;
    private javax.swing.JLabel lblKategorija;
    private javax.swing.JLabel lblKolicina;
    private javax.swing.JLabel lblPopust;
    private javax.swing.JLabel lblPrezimeKupca;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JLabel lblUkupanIznos;
    private javax.swing.JLabel lblUkupanIznos3;
    private javax.swing.JTable tblStavke;
    private javax.swing.JTextField txtCena;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtImeKupca;
    private javax.swing.JTextField txtIznos;
    private javax.swing.JTextField txtKolicina;
    private javax.swing.JTextField txtPopust;
    private javax.swing.JTextField txtPrezimeKupca;
    private javax.swing.JTextField txtTelefon;
    private javax.swing.JTextField txtUkupanIznos;
    // End of variables declaration//GEN-END:variables

    private void prepareTable() {
        try{
            
            StavkaRacunaTableModel model = new StavkaRacunaTableModel(new ArrayList<>());
            tblStavke.setModel(model);
            
            DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();
            cellRenderer.setHorizontalAlignment(SwingConstants.CENTER);
            for(int i = 0; i<tblStavke.getColumnCount(); i++){
                tblStavke.getColumnModel().getColumn(i).setCellRenderer(cellRenderer);
            }
            tblStavke.getColumnModel().getColumn(3).setPreferredWidth(150);
            
        }
        catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Greska prilikom ucitavanja podataka u tabelu!", "Greska!",JOptionPane.ERROR_MESSAGE);
        }
    
    }

    private void fillTracks() {
        cbStaza.setModel(new DefaultComboBoxModel<>(Staza.values()));
    }



    private void fillDate() {
        LocalDate datum = LocalDate.now();
        txtDatum.setText(datum.toString());
    }

    private void fillSectors() {
        cbSektor.setModel(new DefaultComboBoxModel<>(Sektor.values()));
    }

    private void fillDiscount() {
        String cat =(String)cbKategorija.getSelectedItem();
        switch(cat){
            case "REGULAR":
                txtPopust.setText("0%");
                break;
            case "PREMIUM":
                txtPopust.setText("10%");
                break;
            case "VIP":
                txtPopust.setText("20%");
                break;
            default:
                txtPopust.setText("0%");
        }
    }

    private void fillPrice() throws Exception {
        Controller c = new Controller();
        String name = (String) cbTipKarte.getSelectedItem();
        String length = (String) cbTrajanje.getSelectedItem();
        double price = c.vratiCenuKartaTrajanje(name, length);
        txtCena.setText(String.valueOf(price));;
    }

    private void fillTotalPrice() {
        
        double price =Double.parseDouble(txtCena.getText());
        double quantity = Double.parseDouble(txtKolicina.getText());
        if(quantity<1) JOptionPane.showMessageDialog(this, "Unesite sve podatke!","Greska pri unosu podataka!",JOptionPane.ERROR_MESSAGE);
        double totalPrice = price*quantity;
        txtIznos.setText(String.valueOf(totalPrice));
    }
    
    
}
